name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Prepare
        run: |
          npm ci

      - name: Generate Feed
        run: |
          npm run generate-feed

      - name: Build Website
        run: |
          npm run build

      - name: Deploy to GitHub Pages 🚀
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}